version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nestjs-postgres-dev
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_starter
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs-dev-network

networks:
  nestjs-dev-network:
    driver: bridge

volumes:
  postgres-dev-data:
